version: '3.8'

services:
  web:
    # THÊM LẠI LỆNH BUILD để Docker tự đóng gói image từ thư mục chứa mã nguồn
    build: ./docappsystem
    # Đặt tên image nội bộ để dễ quản lý
    image: doctor-appointment-local:latest
    container_name: django_web
    restart: always
    command: gunicorn docappsystem.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=0

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: docaspythondb
      MYSQL_ROOT_PASSWORD: 'Banhmi4o@'
    volumes:
      - db_data:/var/lib/mysql
      # Ánh xạ file SQL từ thư mục cục bộ vào container
      - ./SQLFile/docaspythondb.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'Banhmi4o@'
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: